# Generated by Django 5.0.3 on 2024-03-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес проживания')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('category', models.CharField(choices=[('Друзья', 'Друзья'), ('Семья', 'Семья'), ('Работа', 'Работа')], max_length=10, verbose_name='Категория контакта')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_book_app.contact')),
            ],
        ),
    ]
